### ISSUE TITLE
User manual

### ISSUE THREAD

**Issue by farooquinajam** [AgreementMakerLight/AML-Jar#1]
Dea Sir/ madam

Thank you very much for an excellent software. I need to know minor technical details of using this tool such as how to see console screen as it goes off screen very fast. My ontologies have some rrors which i cant see. 

will be very thankful if someone here in the gorup would, upload a user manual
Thanks

**Comment by farooquinajam** [comment]
![screen](https://cloud.githubusercontent.com/assets/17113264/12875317/7af4cf5e-cdf8-11e5-9bcc-820bbacbe7e1.jpg)

**Comment by AgreementMakerLight** [comment]
Dear Farooquinajam,

I am afraid that we presently do not have a user manual for AML. We do have plans to make one, but we're a small academic team and are currently working on AML mostly in our spare time...
We can assist you in any difficulties you encounter, though.

It is currently not possible to reopen the console screen once it disappears, as it was meant solely as a sort of "progress bar" that shows what is happening during lengthy processes.
I can see that it would be useful to be able to access the console at will, in cases such as yours. However, implementing that functionality will take some time.

In the meantime, a solution to your problem would be to run AML through the command line, as there the error logs when opening the ontology will be written out to the command line screen itself. To do this, open the command line, navigate to AgreementMakerLight folder, then type:
java -jar AgreementMakerLight.jar -s PATH_TO_SOURCE_ONTOLOGY -t PATH_TO_TARGET_ONTOLOGY -a
Since you are only interested in the error logs, you can interrupt AML when the matching process starts (by typing CTRL+C).

If you require further assistance, please let us know.

**Comment by farooquinajam** [comment]
thank you very much for kind reply....

although i was running through command line only. will check with suggested
methods.

thanks instead for reply and a long explainatory email.

Farooqui
